apiVersion: v1
kind: Secret
metadata:
  name: bank-core-secret
  namespace: bank-core
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "bank"
  SPRING_DATASOURCE_PASSWORD: "bank"
  # Demo local: en bancos se integraria con AWS Secrets Manager, External Secrets y cifrado KMS.
