@baseUrl = http://localhost:8080
@customerToken = pega-aqui-el-accessToken-del-login-customer
@operatorToken = pega-aqui-el-accessToken-del-login-operator
@adminToken = pega-aqui-el-accessToken-del-login-admin
@seedCustomerId = 11111111-1111-1111-1111-111111111111
@sourceAccountId = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa
@blockedAccountId = cccccccc-cccc-cccc-cccc-cccccccccccc

### Crear cuenta
POST {{baseUrl}}/api/v1/accounts
Authorization: Bearer {{operatorToken}}
Content-Type: application/json
X-Correlation-ID: http-create-account-001

{
  "customerId": "{{seedCustomerId}}",
  "type": "SAVINGS",
  "currency": "COP",
  "initialBalance": 250000.00
}

### Consultar cuenta
GET {{baseUrl}}/api/v1/accounts/{{sourceAccountId}}
Authorization: Bearer {{customerToken}}
X-Correlation-ID: http-get-account-001

### Consultar saldo
GET {{baseUrl}}/api/v1/accounts/{{sourceAccountId}}/balance
Authorization: Bearer {{customerToken}}
X-Correlation-ID: http-balance-001

### Bloquear cuenta
POST {{baseUrl}}/api/v1/accounts/{{sourceAccountId}}/block
Authorization: Bearer {{operatorToken}}
X-Correlation-ID: http-block-account-001
X-Channel: BRANCH

### Consultar cuenta ya bloqueada
GET {{baseUrl}}/api/v1/accounts/{{blockedAccountId}}
Authorization: Bearer {{operatorToken}}
X-Correlation-ID: http-get-blocked-account-001
