@baseUrl = http://localhost:8080
@customerToken = pega-aqui-el-accessToken-del-login-customer
@operatorToken = pega-aqui-el-accessToken-del-login-operator
@adminToken = pega-aqui-el-accessToken-del-login-admin
@sourceAccountId = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa

### Consultar todos los logs de auditoría como admin
GET {{baseUrl}}/api/v1/audit-logs
Authorization: Bearer {{adminToken}}
X-Correlation-ID: http-audit-all-001

### Consultar logs de auditoría de transferencias como admin
GET {{baseUrl}}/api/v1/audit-logs?entityType=Transfer
Authorization: Bearer {{adminToken}}
X-Correlation-ID: http-audit-transfer-001

### Consultar logs de auditoría de cuenta como operador
GET {{baseUrl}}/api/v1/audit-logs?entityType=Account&entityId={{sourceAccountId}}
Authorization: Bearer {{operatorToken}}
X-Correlation-ID: http-audit-account-001
