@baseUrl = http://localhost:8080
@customerToken = pega-aqui-el-accessToken-del-login-customer
@operatorToken = pega-aqui-el-accessToken-del-login-operator
@adminToken = pega-aqui-el-accessToken-del-login-admin
@seedCustomerId = 11111111-1111-1111-1111-111111111111

### Crear cliente
POST {{baseUrl}}/api/v1/customers
Authorization: Bearer {{operatorToken}}
Content-Type: application/json
X-Correlation-ID: http-create-customer-001

{
  "documentType": "CC",
  "documentNumber": "90000001",
  "fullName": "Laura Demo",
  "email": "laura.demo@example.com"
}

### Consultar cliente inicial
GET {{baseUrl}}/api/v1/customers/{{seedCustomerId}}
Authorization: Bearer {{customerToken}}
X-Correlation-ID: http-get-customer-001

### Consultar productos del cliente
GET {{baseUrl}}/api/v1/customers/{{seedCustomerId}}/products
Authorization: Bearer {{customerToken}}
X-Correlation-ID: http-get-products-001
