@baseUrl = http://localhost:8080
@customerToken = pega-aqui-el-accessToken-del-login-customer
@operatorToken = pega-aqui-el-accessToken-del-login-operator
@adminToken = pega-aqui-el-accessToken-del-login-admin
@seedCustomerId = 11111111-1111-1111-1111-111111111111
@sourceAccountId = aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa

### Consultar movimientos por cuenta
GET {{baseUrl}}/api/v1/accounts/{{sourceAccountId}}/movements
Authorization: Bearer {{customerToken}}
X-Correlation-ID: http-account-movements-001

### Consultar movimientos por cliente
GET {{baseUrl}}/api/v1/customers/{{seedCustomerId}}/movements
Authorization: Bearer {{customerToken}}
X-Correlation-ID: http-customer-movements-001
